ALTER TABLE programs ADD COLUMN IF NOT EXISTS catalog_version VARCHAR(20) NOT NULL DEFAULT '';
ALTER TABLE programs ADD COLUMN IF NOT EXISTS source_url TEXT NOT NULL DEFAULT '';
ALTER TABLE programs ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE program_plan_items ADD COLUMN IF NOT EXISTS course_code VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE program_plan_items ADD COLUMN IF NOT EXISTS category VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE program_plan_items ADD COLUMN IF NOT EXISTS official_term VARCHAR(20) NOT NULL DEFAULT '';
ALTER TABLE program_plan_items ADD COLUMN IF NOT EXISTS source_url TEXT NOT NULL DEFAULT '';
